In [1]:
import pandas as pd
import numpy as np

In [86]:
bill = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ANN/Real_Combine.csv')
bill.head()

      T    TM   Tm     SLP     H   VV    V    VM      PM 2.5
0   7.4   9.8  4.8  1017.6  93.0  0.5  4.3   9.4  219.720833
1   7.8  12.7  4.4  1018.5  87.0  0.6  4.4  11.1  182.187500
2   6.7  13.4  2.4  1019.4  82.0  0.6  4.8  11.1  154.037500
3   8.6  15.5  3.3  1018.7  72.0  0.8  8.1  20.6  223.208333
4  12.4  20.9  4.4  1017.3  61.0  1.3  8.7  22.2  200.645833

In [87]:
bill.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1093 entries, 0 to 1092
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   T       1093 non-null   float64
 1   TM      1093 non-null   float64
 2   Tm      1093 non-null   float64
 3   SLP     1093 non-null   float64
 4   H       1093 non-null   float64
 5   VV      1093 non-null   float64
 6   V       1093 non-null   float64
 7   VM      1093 non-null   float64
 8   PM 2.5  1092 non-null   float64
dtypes: float64(9)
memory usage: 77.0 KB

In [88]:
bill = bill.dropna()

In [89]:
bill.describe()

                 T           TM  ...           VM       PM 2.5
count  1092.000000  1092.000000  ...  1092.000000  1092.000000
mean     26.019963    32.494414  ...    15.809432   109.090984
std       7.232026     6.670017  ...     7.310394    84.465790
min       6.700000     9.800000  ...     1.900000     0.000000
25%      19.300000    27.800000  ...    11.100000    41.833333
50%      28.200000    34.250000  ...    14.800000    83.458333
75%      31.700000    37.000000  ...    18.300000   158.291667
max      38.500000    45.500000  ...    57.600000   404.500000

[8 rows x 9 columns]

In [90]:
x = bill.iloc[:,:8]
y = bill.iloc[:,-1:]

In [91]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state = 100)

In [92]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [93]:
import keras
from keras.models import Sequential
from keras.layers import Dense, ReLU, ELU, Dropout

In [101]:
regressor = Sequential()

In [102]:
regressor.add(Dense(units=5, kernel_initializer='he_uniform', activation='relu', input_dim = 8))

In [103]:
regressor.add(Dense(units=3, kernel_initializer='he_uniform', activation='relu'))

In [104]:
regressor.add(Dense(units=1, activation='linear'))

In [105]:
regressor.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_23 (Dense)            (None, 5)                 45

 dense_24 (Dense)            (None, 3)                 18

 dense_25 (Dense)            (None, 1)                 4

=================================================================
Total params: 67
Trainable params: 67
Non-trainable params: 0
_________________________________________________________________

In [122]:
regressor.compile(optimizer='adam', loss='mae', metrics=['mae'])

In [130]:
model_train = regressor.fit(x_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
88/88 [==============================] - 0s 2ms/step - loss: 35.6247 - mae: 35.6247
Epoch 2/100
88/88 [==============================] - 0s 2ms/step - loss: 35.5868 - mae: 35.5868
Epoch 3/100
88/88 [==============================] - 0s 2ms/step - loss: 35.6120 - mae: 35.6120
Epoch 4/100
88/88 [==============================] - 0s 2ms/step - loss: 35.5829 - mae: 35.5829
Epoch 5/100
88/88 [==============================] - 0s 2ms/step - loss: 35.5613 - mae: 35.5613
Epoch 6/100
88/88 [==============================] - 0s 2ms/step - loss: 35.5558 - mae: 35.5558
Epoch 7/100
88/88 [==============================] - 0s 2ms/step - loss: 35.5825 - mae: 35.5825
Epoch 8/100
88/88 [==============================] - 0s 2ms/step - loss: 35.5722 - mae: 35.5722
Epoch 9/100
88/88 [==============================] - 0s 2ms/step - loss: 35.5485 - mae: 35.5485
Epoch 10/100
88/88 [==============================] - 0s 2ms/step - loss: 35.5434 - mae: 35.5434
Epoch 11/100
88/88 [==============================] - 0s 2ms/step - loss: 35.5391 - mae: 35.5391
Epoch 12/100
88/88 [==============================] - 0s 2ms/step - loss: 35.5129 - mae: 35.5129
Epoch 13/100
88/88 [==============================] - 0s 2ms/step - loss: 35.5087 - mae: 35.5087
Epoch 14/100
88/88 [==============================] - 0s 2ms/step - loss: 35.5120 - mae: 35.5120
Epoch 15/100
88/88 [==============================] - 0s 2ms/step - loss: 35.5055 - mae: 35.5055
Epoch 16/100
88/88 [==============================] - 0s 2ms/step - loss: 35.4826 - mae: 35.4826
Epoch 17/100
88/88 [==============================] - 0s 2ms/step - loss: 35.4899 - mae: 35.4899
Epoch 18/100
88/88 [==============================] - 0s 2ms/step - loss: 35.5154 - mae: 35.5154
Epoch 19/100
88/88 [==============================] - 0s 2ms/step - loss: 35.4772 - mae: 35.4772
Epoch 20/100
88/88 [==============================] - 0s 2ms/step - loss: 35.4762 - mae: 35.4762
Epoch 21/100
88/88 [==============================] - 0s 1ms/step - loss: 35.4593 - mae: 35.4593
Epoch 22/100
88/88 [==============================] - 0s 2ms/step - loss: 35.4629 - mae: 35.4629
Epoch 23/100
88/88 [==============================] - 0s 2ms/step - loss: 35.4650 - mae: 35.4650
Epoch 24/100
88/88 [==============================] - 0s 2ms/step - loss: 35.4417 - mae: 35.4417
Epoch 25/100
88/88 [==============================] - 0s 2ms/step - loss: 35.4382 - mae: 35.4382
Epoch 26/100
88/88 [==============================] - 0s 2ms/step - loss: 35.4339 - mae: 35.4339
Epoch 27/100
88/88 [==============================] - 0s 2ms/step - loss: 35.4262 - mae: 35.4262
Epoch 28/100
88/88 [==============================] - 0s 2ms/step - loss: 35.4561 - mae: 35.4561
Epoch 29/100
88/88 [==============================] - 0s 2ms/step - loss: 35.4236 - mae: 35.4236
Epoch 30/100
88/88 [==============================] - 0s 2ms/step - loss: 35.4004 - mae: 35.4004
Epoch 31/100
88/88 [==============================] - 0s 2ms/step - loss: 35.4248 - mae: 35.4248
Epoch 32/100
88/88 [==============================] - 0s 2ms/step - loss: 35.4229 - mae: 35.4229
Epoch 33/100
88/88 [==============================] - 0s 2ms/step - loss: 35.3662 - mae: 35.3662
Epoch 34/100
88/88 [==============================] - 0s 2ms/step - loss: 35.3869 - mae: 35.3869
Epoch 35/100
88/88 [==============================] - 0s 2ms/step - loss: 35.4130 - mae: 35.4130
Epoch 36/100
88/88 [==============================] - 0s 2ms/step - loss: 35.4188 - mae: 35.4188
Epoch 37/100
88/88 [==============================] - 0s 2ms/step - loss: 35.3796 - mae: 35.3796
Epoch 38/100
88/88 [==============================] - 0s 2ms/step - loss: 35.3849 - mae: 35.3849
Epoch 39/100
88/88 [==============================] - 0s 2ms/step - loss: 35.3596 - mae: 35.3596
Epoch 40/100
88/88 [==============================] - 0s 2ms/step - loss: 35.3498 - mae: 35.3498
Epoch 41/100
88/88 [==============================] - 0s 2ms/step - loss: 35.3575 - mae: 35.3575
Epoch 42/100
88/88 [==============================] - 0s 2ms/step - loss: 35.3430 - mae: 35.3430
Epoch 43/100
88/88 [==============================] - 0s 2ms/step - loss: 35.3530 - mae: 35.3530
Epoch 44/100
88/88 [==============================] - 0s 2ms/step - loss: 35.3488 - mae: 35.3488
Epoch 45/100
88/88 [==============================] - 0s 2ms/step - loss: 35.3380 - mae: 35.3380
Epoch 46/100
88/88 [==============================] - 0s 2ms/step - loss: 35.3693 - mae: 35.3693
Epoch 47/100
88/88 [==============================] - 0s 2ms/step - loss: 35.3327 - mae: 35.3327
Epoch 48/100
88/88 [==============================] - 0s 2ms/step - loss: 35.3273 - mae: 35.3273
Epoch 49/100
88/88 [==============================] - 0s 2ms/step - loss: 35.3419 - mae: 35.3419
Epoch 50/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2954 - mae: 35.2954
Epoch 51/100
88/88 [==============================] - 0s 2ms/step - loss: 35.3019 - mae: 35.3019
Epoch 52/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2974 - mae: 35.2974
Epoch 53/100
88/88 [==============================] - 0s 2ms/step - loss: 35.3020 - mae: 35.3020
Epoch 54/100
88/88 [==============================] - 0s 2ms/step - loss: 35.3001 - mae: 35.3001
Epoch 55/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2884 - mae: 35.2884
Epoch 56/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2871 - mae: 35.2871
Epoch 57/100
88/88 [==============================] - 0s 2ms/step - loss: 35.3068 - mae: 35.3068
Epoch 58/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2744 - mae: 35.2744
Epoch 59/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2778 - mae: 35.2778
Epoch 60/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2659 - mae: 35.2659
Epoch 61/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2712 - mae: 35.2712
Epoch 62/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2587 - mae: 35.2587
Epoch 63/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2659 - mae: 35.2659
Epoch 64/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2718 - mae: 35.2718
Epoch 65/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2606 - mae: 35.2606
Epoch 66/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2571 - mae: 35.2571
Epoch 67/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2599 - mae: 35.2599
Epoch 68/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2268 - mae: 35.2268
Epoch 69/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2492 - mae: 35.2492
Epoch 70/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2358 - mae: 35.2358
Epoch 71/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2334 - mae: 35.2334
Epoch 72/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2428 - mae: 35.2428
Epoch 73/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2000 - mae: 35.2000
Epoch 74/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2265 - mae: 35.2265
Epoch 75/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2127 - mae: 35.2127
Epoch 76/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2039 - mae: 35.2039
Epoch 77/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2037 - mae: 35.2037
Epoch 78/100
88/88 [==============================] - 0s 2ms/step - loss: 35.1986 - mae: 35.1986
Epoch 79/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2146 - mae: 35.2146
Epoch 80/100
88/88 [==============================] - 0s 2ms/step - loss: 35.1880 - mae: 35.1880
Epoch 81/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2100 - mae: 35.2100
Epoch 82/100
88/88 [==============================] - 0s 2ms/step - loss: 35.1833 - mae: 35.1833
Epoch 83/100
88/88 [==============================] - 0s 2ms/step - loss: 35.1888 - mae: 35.1888
Epoch 84/100
88/88 [==============================] - 0s 2ms/step - loss: 35.1876 - mae: 35.1876
Epoch 85/100
88/88 [==============================] - 0s 2ms/step - loss: 35.1691 - mae: 35.1691
Epoch 86/100
88/88 [==============================] - 0s 2ms/step - loss: 35.1649 - mae: 35.1649
Epoch 87/100
88/88 [==============================] - 0s 2ms/step - loss: 35.1921 - mae: 35.1921
Epoch 88/100
88/88 [==============================] - 0s 2ms/step - loss: 35.2366 - mae: 35.2366
Epoch 89/100
88/88 [==============================] - 0s 2ms/step - loss: 35.1417 - mae: 35.1417
Epoch 90/100
88/88 [==============================] - 0s 2ms/step - loss: 35.1380 - mae: 35.1380
Epoch 91/100
88/88 [==============================] - 0s 2ms/step - loss: 35.1336 - mae: 35.1336
Epoch 92/100
88/88 [==============================] - 0s 2ms/step - loss: 35.1271 - mae: 35.1271
Epoch 93/100
88/88 [==============================] - 0s 2ms/step - loss: 35.1334 - mae: 35.1334
Epoch 94/100
88/88 [==============================] - 0s 2ms/step - loss: 35.1388 - mae: 35.1388
Epoch 95/100
88/88 [==============================] - 0s 2ms/step - loss: 35.1183 - mae: 35.1183
Epoch 96/100
88/88 [==============================] - 0s 2ms/step - loss: 35.1453 - mae: 35.1453
Epoch 97/100
88/88 [==============================] - 0s 2ms/step - loss: 35.1502 - mae: 35.1502
Epoch 98/100
88/88 [==============================] - 0s 2ms/step - loss: 35.1173 - mae: 35.1173
Epoch 99/100
88/88 [==============================] - 0s 2ms/step - loss: 35.1320 - mae: 35.1320
Epoch 100/100
88/88 [==============================] - 0s 2ms/step - loss: 35.1075 - mae: 35.1075

In [131]:
predict = regressor.predict(x_test)

In [132]:
from sklearn.metrics import mean_absolute_error, r2_score
print(mean_absolute_error(y_test, predict))
print(r2_score(y_test, predict))

39.6949752337312
0.5871567784486968